### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by WJYw** [PreferredAI/vista-net#1]
Excuse me，the dataset you placed in the google cloud can't send permission requests. Can I get your dataset of VistaNet elsewhere?

**Comment by qtuantruong** [comment]
@WJYw due to some policy of our organization for using google drive, I can not publicly share the link.
Can you give me your email address so that I can grant you access to the data?

**Comment by jiangtaojy** [comment]
Hi. Could you please grant me access to the data, i am currently exploring multimodal sentiment analysis and very interested in your work , my email: taojiang0923@gmail.com. Thank you in advance

**Comment by qtuantruong** [comment]
> Hi. Could you please grant me access to the data, i am currently exploring multimodal sentiment analysis and very interested in your work , my email: [taojiang0923@gmail.com](mailto:taojiang0923@gmail.com). Thank you in advance

I've granted you access to the data. Thanks.

**Comment by kamisamalin** [comment]
Excuse me, could you please grant me access to the data, I am currently exploring multimodal signal analysis and very interested in your work , my email: meina.lin@mail.gdut.edu.cn. Thank you in advance
