### ISSUE TITLE
Request trained weight file

### ISSUE THREAD

**Issue by cuongdothe** [PreferredAI/vista-net#2]
Hi,
Thank Tuan for sharing your work.
Could you please provide your best trained weight file?

**Comment by qtuantruong** [comment]
Hi @cuongdothe ,

I'm not sure how to provide you the best trained weights. However, this is one of the model checkpoints that has the best performance on the validation data:
https://drive.google.com/file/d/1irv6YcbDmgWe4oqq7-XoZ4kJf8f9K-Pj/view?usp=sharing

**Comment by katagoni** [comment]
> Hi @cuongdothe ,
> 
> I'm not sure how to provide you the best trained weights. However, this is one of the model checkpoints that has the best performance on the validation data:
> https://drive.google.com/file/d/1irv6YcbDmgWe4oqq7-XoZ4kJf8f9K-Pj/view?usp=sharing

I cant access ur file could u srnd me a file to email
asd739@daum.net

**Comment by qtuantruong** [comment]
Hi @katagoni ,

Please request for access then I can grant it.
