### ISSUE TITLE
About raw dataset

### ISSUE THREAD

**Issue by ytc272098215** [PreferredAI/vista-net#4]
Hello, I'm currently studying multimodal sentiment analysis and very interested in your brilliant work. I found that your image data have been all extracted by VGG16. But I want to do some more fine-grained observation and exploration of your data set. May I get your raw datasets, please? 
My email: ytc272098215@gmail.com. 
Thank you very much!

**Comment by qtuantruong** [comment]
@ytc272098215 you can obtain the raw photos from [this link](https://drive.google.com/file/d/1h_deGQCHwk94BrRhTUjSE0p_Vxi_L0M6/view?usp=sharing). Please request for access.

**Comment by ytc272098215** [comment]
> @ytc272098215 you can obtain the raw photos from [this link](https://drive.google.com/file/d/1h_deGQCHwk94BrRhTUjSE0p_Vxi_L0M6/view?usp=sharing). Please request for access.

Thank you! That helps me a lot!
