### ISSUE TITLE
Some problem of the performance in the ablation analysis

### ISSUE THREAD

**Issue by yang-233** [PreferredAI/vista-net#5]
![image](https://user-images.githubusercontent.com/31440509/93710510-14b1cd00-fb7a-11ea-9757-fabc3f206ceb.png)
![image](https://user-images.githubusercontent.com/31440509/93710531-3a3ed680-fb7a-11ea-9a2c-682e45753338.png)
The BiRNN's performance in the ablation experiment and the comparison experiment is very different. If the image features are concatenate with the feature vector from text, the performance should not decrease. I want to know the specific difference between them. Thank you!

**Comment by qtuantruong** [comment]
Hi,

Simply concatenating image and text features does not necessarily increase the performance. In fact, that's the motivation why we introduce the visual aspect attention mechanism. Please refer to our discussions (*Comparison to Multimodal Baselines*) in the paper. Thanks!

**Comment by yang-233** [comment]
Thank you for your answer, I read this part of the paper again. and my experiment also confirmed your point,"Simply concatenating image and text features does not necessarily increase the performance." In my experiment, their performance is consistent. So I think your BiRNN performance in the ablation experiment should be consistent with that in the comparison experiment. Can you upload the code for the experimental part? Thank you for your time.

**Comment by qtuantruong** [comment]
The BiRNN in the ablation study is without visual features (i.e., only text input), so it is different from the one in the multimodal baseline comparison. Please simply remove the visual input to recover those baseline models. You can also refer to [this repo](https://github.com/tqtg/hierarchical-attention-networks) for the *soft text attention*.

**Comment by yang-233** [comment]
Thanks a lot.
