### ISSUE TITLE
The data set cannot be found

### ISSUE THREAD

**Issue by Wangkaixinlove** [PreferredAI/vista-net#6]
Could you please send me a data set? The data website you provided cannot be downloaded. Email: 491045545@qq.com. Thank you very much if you can.

**Comment by qtuantruong** [comment]
The link is still alive. You need to have access to Google Drive to be able to download the dataset. Thanks!

**Comment by Wangkaixinlove** [comment]
Thanks for your reply, but the web page reminds me that I need access rights, so I still can't download.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PreferredAI/vista-net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月25日(星期天) 晚上9:41
收件人:&nbsp;"PreferredAI/vista-net"<vista-net@noreply.github.com&gt;;
抄送:&nbsp;"491045545"<491045545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PreferredAI/vista-net] The data set cannot be found (#6)





 
The link is still alive. You need to have access to Google Drive to be able to download the dataset. Thanks!

**Comment by qtuantruong** [comment]
Please request for right access so that we can grant it.

**Comment by Wangkaixinlove** [comment]
Ok, I have applied. Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PreferredAI/vista-net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 晚上10:35
收件人:&nbsp;"PreferredAI/vista-net"<vista-net@noreply.github.com&gt;;
抄送:&nbsp;"491045545"<491045545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PreferredAI/vista-net] The data set cannot be found (#6)





 
Please request for right access so that we can grant it.
