### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by evanmumu** [PreferredAI/vista-net#8]
My email: 1064864716zyt@gmail.com.
Please grant me access to download the dataset, thank you

**Comment by Taotao-la** [comment]
My email: 627514210@qq.com
Please grant me access to download the dataset, thank you

**Comment by WangGeStu** [comment]
My email: 759820708@qq.com
Please grant me access to download the dataset, thank you

**Comment by SilyRab** [comment]
My email:1462831606@qq.com
Please grant me access to download the dataset, thank you very much！
